java_library(
    name = "queue-triage-core-jackson",
    srcs = glob(["src/main/java/**/*.java"]),
    deps =[
        "//common/id:queue-triage-common-id",
        '//lib/jackson:jackson-jaxrs-json-provider',
        '//lib:spring-context',
    ],
    visibility = [
        "PUBLIC"
    ]
)
