java_library(
    name = "queue-triage-core-component-test",
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//common/id:queue-triage-common-id',
        '//core/client:queue-triage-core-client',
        '//core/client-test-support:queue-triage-core-client-test-support',
        '//core/domain:queue-triage-core-domain',
        '//core/jackson:queue-triage-core-jackson',
        '//core/server:queue-triage-core-server',
        '//lib/apache-cxf:cxf-core',
        '//lib/apache-cxf:cxf-rt-rs-client',
        '//lib/apache-cxf:cxf-rt-transports-http',
        '//lib/jackson:jackson-annotations',
        '//lib/jackson:jackson-jaxrs-json-provider',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-context',
        '//lib/spring:spring-web',
        '//lib/slf4j:slf4j-api',
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
    ],
    visibility = [
        "//core/component-test:test"
    ],
)

java_test(
    name = "test",
    srcs = glob(['src/test/java/**/*Test.java']),
    deps = [
        '//common/id:queue-triage-common-id',
        '//common/cxf:queue-triage-cxf',
        '//core/client-test-support:queue-triage-core-client-test-support',
        '//core/component-test:queue-triage-core-component-test',
        '//core/server:queue-triage-core-server',
        '//lib/apache-cxf:cxf-rt-transports-http-jetty',
        '//lib/jackson:jackson-annotations',
        '//lib/javax:javax-servlet-api',
        '//lib/spring:spring-beans',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-test',
        '//lib/test:common',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
    ],
    visibility = [
        "PUBLIC"
    ],
)