java_library(
    name = "queue-triage-core-component-test",
    srcs = glob(['src/main/java/**/*.java']),
    resources = [
        "src/main/resources/application-component-test.yml"
    ],
    resources_root = "src/main/resources",
    deps = [
        '//common/id:queue-triage-common-id',
        '//common/jackson:queue-triage-common-jackson',
        '//common/jgiven:jgiven',
        '//core/activemq:queue-triage-core-activemq',
        '//core/client:queue-triage-core-client',
        '//core/client-test-support:queue-triage-core-client-test-support',
        '//core/dao-mongo-test-support:queue-triage-core-dao-mongo-test-support',
        '//core/domain:queue-triage-core-domain',
        '//core/message-classification:queue-triage-core-message-classification',
        '//core/server:server',
        '//lib/activemq:activemq-client',
        '//lib/activemq:geronimo-jms',
        '//lib/apache-cxf:cxf-core',
        '//lib/apache-cxf:cxf-rt-rs-client',
        '//lib/apache-cxf:cxf-rt-transports-http',
        '//lib/jackson:jackson-annotations',
        '//lib/jackson:jackson-jaxrs-json-provider',
        '//lib/javax:javax-ws-rs-api',
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-boot-with-dependencies',
        '//lib/spring:spring-jms',
        '//lib/spring:spring-test',
        '//lib/spring:spring-tx',
        '//lib/spring:spring-web',
        '//lib/test:awaitility',
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
        '//lib/test:hamcrest-optional',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
        '//lib/test:junit',
    ],
    visibility = [
        "//core/component-test:test"
    ],
)

java_test(
    name = "test",
    labels = [
        "component-test"
    ],
    srcs = glob(['src/test/java/**/*Test.java']),
    deps = [
        "//lib/hibernate-validator:hibernate-validator",
        '//common/cxf-server:queue-triage-common-cxf-server',
        '//common/id:queue-triage-common-id',
        '//common/jgiven:jgiven',
        '//core/client:queue-triage-core-client',
        '//core/client-test-support:queue-triage-core-client-test-support',
        '//core/component-test:queue-triage-core-component-test',
        '//core/message-classification:queue-triage-core-message-classification-server',
        '//core/resend:queue-triage-core-resend-spring',
        '//core/server:server',
        '//lib/activemq:activemq-broker-with-dependencies',
        '//lib/activemq:activemq-client-with-dependencies',
        '//lib/apache-cxf:cxf-rt-transports-http-jetty',
        '//lib/jackson:jackson-annotations',
        '//lib/javax:javax-servlet-api',
        '//lib/spring:spring-beans',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-test',
        '//lib/spring:spring-tx',
        '//lib/test:common',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
    ],
    visibility = [
        "PUBLIC"
    ],
    # TODO: Can we pass $(location :test) or something similar into vm_args?
    vm_args = [
        "-Djgiven.report.dir=buck-out/gen/core/component-test/jgiven-reports",
    ],
)

# buck build //core/component-test:generate-jgiven-html-reports
genrule(
    name = "generate-jgiven-html-reports",
    cmd  = "$(exe //lib/test:jgiven-html5-report-with-deps) --format=html --sourceDir=`pwd`/../jgiven-reports --targetDir=$OUT",
    out  = "jgiven-html-reports",
)