java_library(
    name = "queue-triage-core-component-test",
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
        '//lib:spring-beans',
        '//lib:spring-boot',
        '//lib:spring-boot-test',
        '//lib:spring-context',
        '//lib:spring-core',
        '//lib:spring-web',
    ],
    visibility = [
        "PUBLIC"
    ],
)

java_test(
    name = "test",
    srcs = glob(['src/test/java/**/*Test.java']),
    deps = [
        '//core/server:queue-triage-core-server',
        '//core/component-test:queue-triage-core-component-test',
        '//lib/test:common',
        '//lib/javax:javax-servlet-api',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
        '//lib:spring-beans',
        '//lib:spring-boot-test',
        '//lib:spring-test',
    ],
    visibility = [
        "PUBLIC"
    ],
)