java_library(
    name = "main",
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//lib:hamcrest-core',
        '//lib:hamcrest-library',
        '//lib:jgiven-core',
        '//lib:jgiven-spring',
        '//lib:spring-beans',
        '//lib:spring-boot',
        '//lib:spring-boot-test',
        '//lib:spring-context',
        '//lib:spring-core',
        '//lib:spring-web',
    ],
    visibility = [
        "PUBLIC"
    ]
)

java_test(
    name = "test",
    srcs = glob(['src/test/java/**/*Test.java']),
    deps = [
        '//queue-triage-core/queue-triage-core-server:main',
        '//queue-triage-core/queue-triage-core-component-test:main',
        '//lib:common-test',
        '//lib:hibernate-validator-incl-deps',
        '//lib:javax-servlet-api',
        '//lib:javax-validation-api',
        '//lib:jgiven',
        '//lib:jgiven-spring',
        '//lib:spring-beans',
        '//lib:spring-boot-test',
        '//lib:spring-test',
    ],
    visibility = [
        "PUBLIC"
    ],
)