java_library(
    name = 'test-lib-main',
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        "//common/id:queue-triage-common-id",
        '//queue-triage-core/queue-triage-core-domain:queue-triage-core-domain',
        '//lib:hamcrest-core',
        '//lib:hamcrest-library',
    ],
    visibility = [
        # Ideally I would like to limit this to test modules only
        'PUBLIC'
    ],
)