java_library(
    name =  'queue-triage-common-executor',
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        '//lib/slf4j:slf4j-api',
    ],
    # TODO: Drop the visibility
    visibility = [
        "PUBLIC",
    ]
)