java_library(
    name = "queue-triage-core-client",
    srcs = glob(["src/main/java/**/*.java"]),
    deps =[
        '//common/id:queue-triage-common-id',
        '//lib:commons-lang3',
        '//lib/jackson:jackson-annotations',
        '//lib/javax:javax-ws-rs-api',
    ],
    visibility = [
        "//core/server:queue-triage-core-server",
        "//core/server:test",
        "//web:queue-triage-web",
    ]
)
