java_library(
    name = "queue-triage-core-client",
    srcs = glob(["src/main/java/**/*.java"]),
    deps =[
        '//common/id:queue-triage-common-id',
        '//lib:commons-lang3',
        '//lib:hibernate-validator',
        '//lib:jackson-annotations',
        '//lib:javax-ws-rs-api',
        '//lib:javax-validation-api',
    ],
    visibility = [
        "//core/server:queue-triage-core-server",
        "//core/server:test",
        "//web:queue-triage-web",
    ]
)
