server:
  port: 9991
  metrics:
    enabled: true
    prefix: uk.gov.dwp.queue.triage.core.servlet

cxf:
  contextPath: /core
  metrics:
    enabled: true
    prefix: uk.gov.dwp.queue.triage.core.cxf

dao:
  mongo:
    serverAddresses:
      - host: localhost
        port: 27017
    options:
      ssl:
        enabled: false
        invalidHostnameAllowed: false
    dbName: queue-triage
    failedMessage:
      name: failedMessage
      username: failedMessageUser
      password: Passw0rd
#      password: "VAULT(/path/secret/Passw0rd)"


jms:
  activemq:
    brokers:
      - name: internal-broker
        url: tcp://localhost:61616
        queue: ActiveMQ.DLQ
        resend:
          frequency: 60
          timeUnit: SECONDS

messageClassification:
  initialDelay: 0
  frequency: 60
  timeUnit: SECONDS

#vault:
#  address: http://localhost:1234/vault
#  openTimeout: 20 #seconds
#  readTimeout: 20 #seconds
#  tokenAuthentication:
#    tokenPath: /var/lib/.vault
#  ssl:
#    sslPemFilePath: /etc/application/vault.pem
#    sslVerify: true
