java_library(
    name = "queue-triage-web-component-test",
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//common/id:queue-triage-common-id',
        '//common/jgiven:jgiven',
        '//common/ldap-test-support:queue-triage-ldap-test-support',
        '//core/client:queue-triage-core-client',
        '//core/client-test-support:queue-triage-core-client-test-support',
        "//lib/ldap:unboundid-ldapsdk",
        '//lib/selenide:selenide',
        '//lib/selenium:selenium-api',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-boot-with-dependencies',
        '//lib/spring:spring-test',
        '//lib/spring:spring-web',
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
        '//lib/test:mockito-core',
    ],
    visibility = [
        "//web/component-test:test"
    ]
)

test_deps = [
    '//common/jgiven:jgiven',
    '//core/client-test-support:queue-triage-core-client-test-support',
    "//lib/hibernate-validator:hibernate-validator",
    '//lib/selenide:selenide',
    '//lib/selenide:selenide-dependencies',
    '//lib/spring:spring-beans',
    '//lib/spring:spring-boot-test',
    '//lib/spring:spring-context',
    '//lib/spring:spring-test',
    '//lib/test:common',
    '//lib/test:jgiven',
    '//lib/test:jgiven-spring',
    '//web/component-test:queue-triage-web-component-test',
    '//web/server:server',
]

vm_args = [
    '-Djgiven.report.dir=buck-out/gen/web/component-test/jgiven-reports',
    '-Dselenide.reports=buck-out/gen/web/component-test/selenide-output'
]

def firefox(vm_args, test_deps):
    vm_args.append('-Dbrowser=firefox')
    vm_args.append('-Dwebdriver.gecko.driver=lib/geckodriver/geckodriver')
    test_deps.append('//lib/selenium/firefox-driver:selenium-firefox-driver-with-dependencies')

def phantomjs(vm_args, test_deps):
    vm_args.append('-Dbrowser=phantomjs')
    vm_args.append('-Dphantomjs.binary.path=lib/selenium/phantomjs-driver/phantomjs')
    test_deps.append('//lib/selenium/phantomjs-driver:phantomjs-driver-with-dependencies')

browsers = {
    'firefox': firefox,
    'phantomjs': phantomjs
}

# Configure the 'vm_args' and 'deps' for the relevant browser
browsers[read_config('selenium', 'browser', 'firefox')](vm_args, test_deps)
remote_url = read_config('selenium', 'remote_url')
if remote_url:
    vm_args.append('-Dremote={}'.format(remote_url))

# The web component-test will run against a local firefox.  There are a number of options that can
# be configuration by adding a [selenium] section to a .buckconfig.local file.  See the README.md
# for more details.
java_test(
    name = "test",
    labels = [
        "component-test"
    ],
    srcs = glob(['src/test/java/**/*Test.java']),
    deps = test_deps,
    vm_args = vm_args
)

# buck build //web/component-test:generate-jgiven-html-reports
genrule(
    name = "generate-jgiven-html-reports",
    cmd  = "$(exe //lib/test:jgiven-html5-report-with-deps) --format=html --sourceDir=`pwd`/../jgiven-reports --targetDir=$OUT",
    out  = "jgiven-html-reports",
)
