java_library(
    name = "queue-triage-web-component-test",
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-boot-with-dependencies',
        '//lib/spring:spring-web',
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
    ],
    visibility = [
        "//web/component-test:test"
    ]
)

java_test(
    name = "test",
    srcs = glob(['src/test/java/**/*Test.java']),
    deps = [
        '//lib/spring:spring-beans',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-test',
        '//lib/test:common',
        '//lib/test:jgiven',
        '//lib/test:jgiven-spring',
        '//web/component-test:queue-triage-web-component-test',
        '//web/server:queue-triage-web-server',
    ]
)