java_library(
    name = 'test-lib-main',
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//queue-triage-core/queue-triage-core-client:main',
        '//lib:hamcrest-core',
        '//lib:hamcrest-library',
    ],
    visibility = [
        # Ideally I would like to limit this to test modules only
        'PUBLIC'
    ],
)