java_library(
    name = "queue-triage-common-matchers",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        "//lib:commons-lang3",
        "//lib/test:hamcrest-core",
    ],
    visibility = [
        "PUBLIC"
    ]
)