java_library(
    name = "queue-triage-ldap-test-support",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = [
        "src/main/resources/example.ldif"
    ],
    resources_root = 'src/main/resources',
    exported_deps = [
        "//lib/ldap:unboundid-ldapsdk",
        "//lib/slf4j:slf4j-api",
    ],
    visibility = [
        "PUBLIC"
    ],
)

genrule(
    name = "start",
    cmd = "java -cp $(classpath :queue-triage-ldap-test-support) uk.gov.dwp.queue.triage.ldap.InMemoryDirectoryServerFactory > $OUT",
    out = "startMicroservice.log",
    executable = True,
)
