java_library(
    name = "queue-triage-ldap-test-support",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = [
        "src/main/resources/example.ldif"
    ],
    resources_root = 'src/main/resources',
    deps = [
        "//lib/ldap:unboundid-ldapsdk",
        "//lib/slf4j:slf4j-api",
    ],
    visibility = [
        "PUBLIC"
    ],
)

genrule(
    name = "start-script",
    cmd  = "echo 'java -cp $(classpath :queue-triage-ldap-test-support) uk.gov.dwp.queue.triage.ldap.InMemoryDirectoryServerFactory' > $OUT && chmod u+x $OUT",
    out  = "start-ldap.sh",
)
