java_library(
    name = 'queue-triage-core-domain-test-support',
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        "//common/id:queue-triage-common-id",
        '//core/domain:queue-triage-core-domain',
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
    ],
    visibility = [
        "//core/dao-mongo:test",
        "//core/server:test",
    ],
)