java_library(
    name = 'queue-triage-core-domain-test-support',
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        "//common/id:queue-triage-common-id",
        '//core/domain:queue-triage-core-domain',
        '//lib:hamcrest-core',
        '//lib:hamcrest-library',
    ],
    visibility = [
        # Ideally I would like to limit this to test modules only
        'PUBLIC'
    ],
)