java_library(
    name = "main",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        '//queue-triage-core/queue-triage-core-client:main',
    ],
    visibility = [
        "PUBLIC"
    ]
)
