prebuilt_jar(
    name='awaitility',
    binary_jar=':awaitility-mvn',
    visibility=[
        '//core/component-test:queue-triage-core-component-test',
    ])
prebuilt_jar(name='byte-buddy', binary_jar=':byte-buddy-mvn')
prebuilt_jar(name='hamcrest-core', binary_jar=':hamcrest-core-mvn', visibility=["PUBLIC"])
prebuilt_jar(name='hamcrest-library', binary_jar=':hamcrest-library-mvn', visibility=["PUBLIC"])
prebuilt_jar(name='hamcrest-optional', binary_jar=':hamcrest-optional-mvn', visibility=["PUBLIC"])
prebuilt_jar(name='jansi', binary_jar=':jansi-mvn')
prebuilt_jar(name='jgiven-core', binary_jar=':jgiven-core-mvn')
prebuilt_jar(name='jgiven-junit', binary_jar=':jgiven-junit-mvn')
prebuilt_jar(name='jgiven-html5-report', binary_jar=':jgiven-html5-report-mvn')
prebuilt_jar(name='jgiven-spring', binary_jar=':jgiven-spring-mvn', visibility=["PUBLIC"])
prebuilt_jar(name='junit', binary_jar=':junit-mvn', visibility=["PUBLIC"])
prebuilt_jar(name='mockito-core', binary_jar=':mockito-core-mvn')
prebuilt_jar(name='objenesis', binary_jar=':objenesis-mvn')
prebuilt_jar(name='paranamer', binary_jar=':paranamer-mvn')

remote_file(name='awaitility-mvn', out='awaitility-3.0.0.jar', url='mvn:org.awaitility:awaitility:jar:3.0.0', sha1='7e6b79f2b1e57eaa967b229791f31ca55aea668a')
remote_file(name='byte-buddy-mvn', out='byte-buddy-1.6.14.jar', url='mvn:net.bytebuddy:byte-buddy:jar:1.6.14', sha1='871c3e49dc6183d0d361601c2f1d11abb1a6b48c')
remote_file(name='hamcrest-core-mvn', out='hamcrest-core-1.3.jar', url='mvn:org.hamcrest:hamcrest-core:jar:1.3', sha1='42a25dc3219429f0e5d060061f71acb49bf010a0')
remote_file(name='hamcrest-library-mvn', out='hamcrest-library-1.3.jar', url='mvn:org.hamcrest:hamcrest-library:jar:1.3', sha1='4785a3c21320980282f9f33d0d1264a69040538f')
remote_file(name='hamcrest-optional-mvn', out='hamcrest-optional-1.0.2.jar', url='mvn:com.spotify:hamcrest-optional:jar:1.0.2', sha1='7b5261ec45db30fad35847022bd89901b7216df4')
remote_file(name='jansi-mvn', out='jansi-1.15.jar', url='mvn:org.fusesource.jansi:jansi:jar:1.15', sha1='5292bc138cb1412ea940551c667f8ec4da52d249')
remote_file(name='jgiven-core-mvn', out='jgiven-core-0.15.1.jar', url='mvn:com.tngtech.jgiven:jgiven-core:jar:0.15.1', sha1='fc2880aa9d74adc6f8a72b5696439d13b8f530dc')
remote_file(name='jgiven-html5-report-mvn', out='jgiven-html5-report-0.15.1.jar', url='mvn:com.tngtech.jgiven:jgiven-html5-report:jar:0.15.1', sha1='6d011ce29cdf5f6ab1c5863ba523fa9973463b29')
remote_file(name='jgiven-junit-mvn', out='jgiven-junit-0.15.1.jar', url='mvn:com.tngtech.jgiven:jgiven-junit:jar:0.15.1', sha1='0b862638480787929088efb28632d212a6701fa2')
remote_file(name='jgiven-spring-mvn', out='jgiven-spring-0.15.1.jar', url='mvn:com.tngtech.jgiven:jgiven-spring:jar:0.15.1', sha1='312abfa016e04e88fe73e4a97fcc396534c82d9d')
remote_file(name='junit-mvn', out='junit-4.12.jar', url='mvn:junit:junit:jar:4.12', sha1='2973d150c0dc1fefe998f834810d68f278ea58ec')
remote_file(name='mockito-core-mvn', out='mockito-core-2.8.9.jar', url='mvn:org.mockito:mockito-core:jar:2.8.9', sha1='1afb35b2d77d40567756c379e54c18da3574a96e')
remote_file(name='objenesis-mvn', out='objenesis-2.5.1.jar', url='mvn:org.objenesis:objenesis:jar:2.5.1', sha1='272bab9a4e5994757044d1fc43ce480c8cb907a4')
remote_file(name='paranamer-mvn', out='paranamer-2.8.jar', url='mvn:com.thoughtworks.paranamer:paranamer:jar:2.8', sha1='619eba74c19ccf1da8ebec97a2d7f8ba05773dd6')

java_library(
    name = 'common',
    deps = [],
    exported_deps = [
        ':byte-buddy',
        ':hamcrest-core',
        ':hamcrest-library',
        ':junit',
        ':mockito-core',
        ':objenesis',
    ],
    visibility = [
        "PUBLIC",
    ],
)

java_library(
    name = 'jgiven',
    deps = [],
    exported_deps = [
        ':jansi',
        ':jgiven-core',
        ':jgiven-html5-report',
        ':jgiven-junit',
        ':paranamer',
        '//lib:gson',
        '//lib:guava',
    ],
    visibility = [
        "PUBLIC",
    ],
)
