java_library(
    name = "main",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        '//queue-triage-core/queue-triage-core-client:main',
        '//queue-triage-core/queue-triage-core-dao:main',
        '//queue-triage-core/queue-triage-core-jackson:main',
        '//lib:jackson-databind',
        '//lib:mongodb-driver-incl-deps',
        '//lib:spring-beans',
        '//lib:spring-boot',
        '//lib:spring-context',
    ],
    visibility = [
        '//queue-triage-core/queue-triage-core-dao-mongo-test-support:test-lib-main',
        '//queue-triage-core/queue-triage-core-server:main',
    ]
)

java_test(
    name = 'test',
    srcs = glob([ 'src/test/java/**/*Test.java']),
    deps = [
        '//queue-triage-core/queue-triage-core-client:main',
        '//queue-triage-core/queue-triage-core-client-test-support:test-lib-main',
        '//queue-triage-core/queue-triage-core-dao:main',
        '//queue-triage-core/queue-triage-core-dao-mongo:main',
        '//queue-triage-core/queue-triage-core-dao-mongo-test-support:test-lib-main',
        '//lib:common-test',
        '//lib:commons-logging',
        '//lib:hibernate-validator-incl-deps',
        '//lib:mongodb-driver-incl-deps',
        '//lib:spring-aop',
        '//lib:spring-beans',
        '//lib:spring-boot-autoconfigure',
        '//lib:spring-boot-test',
        '//lib:spring-context',
        '//lib:spring-core',
        '//lib:spring-expression',
        '//lib:spring-test',
    ],
    visibility = [
    ]
)