java_library(
    name = 'queue-triage-core-client-test-support',
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//common/id:queue-triage-common-id',
        '//core/client:queue-triage-core-client',
        '//lib:commons-lang3',
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
        '//lib/test:jgiven-core',
    ],
    visibility = [
        '//core/client:test',
        '//core/component-test/...',
        '//core/resend:test',
        '//core/server:test',
        '//web/component-test/...',
        '//web/server:test',
    ],
)