server:
  port: 9990

cxf:
  contextPath: /web

client:
  core:
    url: http://localhost:9991/core

ldap:
  urls:
    - ldap://localhost:8389/

vault:
  address: http://boom/boom
  readTimeout: 20
  openTimeout: 20
  tokenAuthentication:
    tokenPath: /var/lib/.tokenz