java_library(
    name = "queue-triage-health",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        '//lib/javax:javax-servlet-api',
    ],
    visibility = [
        "//common/health:test",
        "//core/server:server",
        "//web/server:server",
    ]
)

java_test(
    name = "test",
    srcs = glob(['src/test/java/**/*Test.java']),
    deps = [
        '//common/health:queue-triage-health',
        '//lib/javax:javax-servlet-api',
        '//lib/test:common',
    ],
)


