java_library(
    name = "queue-triage-common-id",
    srcs = glob(["**/*.java"]),
    exported_deps = [
        '//lib/jackson:jackson-annotations',
    ],
    visibility = [
        "PUBLIC",
    ],
)