java_library(
    name = "queue-triage-web",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        '//core/client:queue-triage-core-client',
    ],
    visibility = [
        "PUBLIC"
    ]
)
